name: Convert Markdown to PDF

on:
  push:
    branches:
      - "main"
    paths:
      - "RESUME.md"
  workflow_dispatch:

jobs:
  convert-md-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js and Chromium
        run: |
          sudo apt update
          sudo apt install -y nodejs npm chromium-browser libx11-xcb1 libxtst6 libxrandr2

      - name: Install md-to-pdf
        run: npm install -g md-to-pdf puppeteer

      - name: Set Puppeteer Environment Variables
        run: |
          echo "PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser" >> $GITHUB_ENV
          echo "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true" >> $GITHUB_ENV

      - name: Convert Markdown to PDF
        run: md-to-pdf RESUME.md

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: RESUME.pdf
